# https://github.com/jekyll/minima
markdown: GFM
theme: minima
title: 'rm -rf /*'
author:
  name: Voidbalance
  email: me@voidbalance.com
description: >
  Carpe diem
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: solarized
  date_format: "%b %-d, %Y"
